NDefines.NGameplay.GROUND_SUPPORT_SOFT_DMG = 0.05 -- Multiplier to fortification damage
NDefines.NGameplay.GROUND_SUPPORT_LIMITED_DMG = 0.25 -- Multiplier to fortification damage
NDefines.NGameplay.GROUND_SUPPORT_FULL_DMG = 0.75 -- Multiplier to fortification damage
NDefines.NGameplay.PLANET_ARMIES_LIMIT = 30
NDefines.NGameplay.GARRISON_SIZE_BASE = 1		-- Planet always spawns this number of garrisons
NDefines.NGameplay.GARRISON_SIZE_MULT = 0.6		-- Per pop over 1
NDefines.NGameplay.PLANET_FORTIFICATION_BASE = 500		-- Planet always has this much fortification health
NDefines.NGameplay.PLANET_FORTIFICATION_MULT = 200		-- Per pop over 1
NDefines.NGameplay.PLANET_FORTIFICATION_DEFENSE_BONUS = 5		-- At 100% fortification, divide damage to defending armies by this
NDefines.NGameplay.PLANET_FORTIFICATION_DEFENSE_MIN = 1.0		-- At 0% fortification, divide damage to defending armies by this
NDefines.NGameplay.PLANET_FORTIFICATION_REPAIR = 1.0		-- Each day
NDefines.NGameplay.PLANET_FORTIFICATION_REPAIR_DELAY = 90	-- Days since being bombarded before repairs to fortifications start
NDefines.NArmy.BASE_MAINTENANCE_FACTOR = 1				-- global base maintenance cost
NDefines.NArmy.REINFORCE_MAINTENANCE_FACTOR = 2.50				-- 50% increase of maintenance cost
NDefines.NArmy.MONTHLY_REINFORCE = 0.1				-- Monthly health percentage reinforcement of armies
NDefines.NArmy.BASE_HEALTH = 500.0			-- Base health
NDefines.NArmy.BASE_DAMAGE_MIN = 1.0				-- Base min damage
NDefines.NArmy.BASE_DAMAGE_MAX = 3.0				-- Base max damage
NDefines.NArmy.BASE_MORALE = 250.0			-- Base morale
NDefines.NArmy.MORALE_DAMAGE_MULT = 1.0				-- Morale Damage Multiplier, how much of damage is also dealt to morale.
NDefines.NArmy.MONTHLY_MORALE_REGENERATION = 0.02				-- How much morale this unit regenerates each month, percentage of max value.
NDefines.NArmy.EXP_EXPERIENCED = 200				-- Amount of exp to reach experienced rank
NDefines.NArmy.EXP_VETERAN = 1000				-- Amount of exp to reach veteran rank
NDefines.NArmy.EXP_ELITE = 10000			-- Amount of exp to reach elite rank
NDefines.NArmy.NUM_DAYS_BEFORE_RETREAT = 3				-- How many days that need to pass before we can retreat.
NDefines.NArmy.ATTACHMENT_SLOTS = 2
NDefines.NAI.TRANSPORT_FLEET_SIZE = 30					-- AI will have transport fleets of this size